// Mock data for Customers module
export const mockCustomers = [
    {
        id: "1",
        customerCode: "CUST-1001",
        name: "Ahmet Yılmaz",
        email: "ahmet.yilmaz@email.com",
        phone: "+90 532 123 4567",
        address: "Atatürk Caddesi No:123, Kadıköy, İstanbul",
        city: "İstanbul",
        category: "VIP",
        status: "active",
        totalOrders: 42,
        totalSpent: 12450.50,
        loyaltyPoints: 1245,
        lastOrderDate: "2024-01-20",
        churnRisk: "low",
        avatar: "https://ui-avatars.com/api/?name=Ahmet+Yilmaz&background=004aad&color=fff",
        satisfaction: 9.8,
        tags: ["Sadık Müşteri", "Yüksek Hacim", "Sabah Tercihli"],
    },
    {
        id: "2",
        customerCode: "CUST-1002",
        name: "Ayşe Kaya",
        email: "ayse.kaya@email.com",
        phone: "+90 544 234 5678",
        address: "İstiklal Sokak No:45, Beşiktaş",
        city: "İstanbul",
        category: "Regular",
        status: "active",
        totalOrders: 15,
        totalSpent: 4500.00,
        loyaltyPoints: 450,
        lastOrderDate: "2024-01-18",
        churnRisk: "medium",
        avatar: "https://ui-avatars.com/api/?name=Ayse+Kaya&background=10b981&color=fff",
        satisfaction: 8.5,
        tags: ["Menü Takipçi", "Haftalık"],
    },
    {
        id: "3",
        customerCode: "CUST-1003",
        name: "Mehmet Demir",
        email: "mehmet.demir@email.com",
        phone: "+90 505 345 6789",
        address: "Meydan cd. Üsküdar",
        city: "İstanbul",
        category: "New",
        status: "active",
        totalOrders: 2,
        totalSpent: 350.75,
        loyaltyPoints: 35,
        lastOrderDate: "2024-01-15",
        churnRisk: "high",
        avatar: "https://ui-avatars.com/api/?name=Mehmet+Demir&background=f59e0b&color=fff",
        satisfaction: 7.2,
        tags: ["Potansiyel VIP"],
    },
    {
        id: "4",
        customerCode: "CUST-1004",
        name: "Canan Öz",
        email: "canan.oz@email.com",
        phone: "+90 530 456 7890",
        address: "Bağdat Cd. No:200, Şaşkınbakkal",
        city: "İstanbul",
        category: "VIP",
        status: "inactive",
        totalOrders: 28,
        totalSpent: 9200.00,
        loyaltyPoints: 920,
        lastOrderDate: "2023-12-05",
        churnRisk: "high",
        avatar: "https://ui-avatars.com/api/?name=Canan+Oz&background=6366f1&color=fff",
        satisfaction: 9.0,
        tags: ["Eski Sadık", "İndirim Bekleyen"],
    }
];

export const customerStats = {
    total: 1250,
    active: 840,
    vip: 45,
    newThisMonth: 12,
    totalRevenue: 245000,
    avgSatisfaction: 8.9,
};
