// Mock data for E-commerce modules

export const mockEcommerceSales = [
  {
    id: "1",
    orderNumber: "EC-2024-001",
    platform: "Trendyol",
    customerName: "Ahmet Yılmaz",
    productName: "Tavuk Döner",
    quantity: 2,
    unitPrice: 45.0,
    total: 90.0,
    commission: 4.5,
    netAmount: 85.5,
    orderDate: new Date("2024-10-19T14:30:00"),
    status: "DELIVERED",
  },
  {
    id: "2",
    orderNumber: "EC-2024-002",
    platform: "Hepsiburada",
    customerName: "Mehmet Kaya",
    productName: "Köfte Menü",
    quantity: 1,
    unitPrice: 65.0,
    total: 65.0,
    commission: 3.25,
    netAmount: 61.75,
    orderDate: new Date("2024-10-19T12:15:00"),
    status: "SHIPPED",
  },
  {
    id: "3",
    orderNumber: "EC-2024-003",
    platform: "Trendyol",
    customerName: "Ayşe Demir",
    productName: "Lahmacun",
    quantity: 5,
    unitPrice: 15.0,
    total: 75.0,
    commission: 3.75,
    netAmount: 71.25,
    orderDate: new Date("2024-10-18T16:45:00"),
    status: "DELIVERED",
  },
  {
    id: "4",
    orderNumber: "EC-2024-004",
    platform: "N11",
    customerName: "Fatma Özkan",
    productName: "Pide",
    quantity: 3,
    unitPrice: 35.0,
    total: 105.0,
    commission: 5.25,
    netAmount: 99.75,
    orderDate: new Date("2024-10-18T10:20:00"),
    status: "PENDING",
  },
  {
    id: "5",
    orderNumber: "EC-2024-005",
    platform: "Hepsiburada",
    customerName: "Ali Çelik",
    productName: "Tavuk Döner",
    quantity: 1,
    unitPrice: 45.0,
    total: 45.0,
    commission: 2.25,
    netAmount: 42.75,
    orderDate: new Date("2024-10-17T18:30:00"),
    status: "DELIVERED",
  },
];

export const mockReconciliations = [
  {
    id: "1",
    platform: "Trendyol",
    period: "Ekim 2024",
    totalSales: 12500.0,
    totalCommission: 625.0,
    netAmount: 11875.0,
    paidAmount: 11875.0,
    pendingAmount: 0,
    status: "RECONCILED",
    reconciliationDate: new Date("2024-11-05"),
  },
  {
    id: "2",
    platform: "Hepsiburada",
    period: "Ekim 2024",
    totalSales: 8500.0,
    totalCommission: 425.0,
    netAmount: 8075.0,
    paidAmount: 8075.0,
    pendingAmount: 0,
    status: "RECONCILED",
    reconciliationDate: new Date("2024-11-05"),
  },
  {
    id: "3",
    platform: "N11",
    period: "Ekim 2024",
    totalSales: 3200.0,
    totalCommission: 160.0,
    netAmount: 3040.0,
    paidAmount: 2000.0,
    pendingAmount: 1040.0,
    status: "PENDING",
    reconciliationDate: null,
  },
  {
    id: "4",
    platform: "Trendyol",
    period: "Eylül 2024",
    totalSales: 15200.0,
    totalCommission: 760.0,
    netAmount: 14440.0,
    paidAmount: 14440.0,
    pendingAmount: 0,
    status: "RECONCILED",
    reconciliationDate: new Date("2024-10-05"),
  },
  {
    id: "5",
    platform: "Hepsiburada",
    period: "Eylül 2024",
    totalSales: 9800.0,
    totalCommission: 490.0,
    netAmount: 9310.0,
    paidAmount: 9310.0,
    pendingAmount: 0,
    status: "RECONCILED",
    reconciliationDate: new Date("2024-10-05"),
  },
];

export const mockCustomerQuestions = [
  {
    id: "1",
    platform: "Trendyol",
    customerName: "Ahmet Yılmaz",
    productName: "Tavuk Döner",
    question: "Ürün ne zaman teslim edilir?",
    answer: "Siparişiniz 1-2 iş günü içinde teslim edilir.",
    status: "ANSWERED",
    createdAt: new Date("2024-10-19T10:00:00"),
    answeredAt: new Date("2024-10-19T10:30:00"),
  },
  {
    id: "2",
    platform: "Hepsiburada",
    customerName: "Mehmet Kaya",
    productName: "Köfte Menü",
    question: "Ürün dondurulmuş mu?",
    answer: null,
    status: "PENDING",
    createdAt: new Date("2024-10-19T14:00:00"),
    answeredAt: null,
  },
  {
    id: "3",
    platform: "Trendyol",
    customerName: "Ayşe Demir",
    productName: "Lahmacun",
    question: "Gluten içeriyor mu?",
    answer: "Evet, lahmacun hamuru buğday unu içermektedir.",
    status: "ANSWERED",
    createdAt: new Date("2024-10-18T09:00:00"),
    answeredAt: new Date("2024-10-18T09:15:00"),
  },
  {
    id: "4",
    platform: "N11",
    customerName: "Fatma Özkan",
    productName: "Pide",
    question: "Vegan mı?",
    answer: null,
    status: "PENDING",
    createdAt: new Date("2024-10-18T16:00:00"),
    answeredAt: null,
  },
  {
    id: "5",
    platform: "Hepsiburada",
    customerName: "Ali Çelik",
    productName: "Tavuk Döner",
    question: "Soğuk zincir korunuyor mu?",
    answer: "Evet, tüm ürünlerimiz soğuk zincir koruması altında gönderilmektedir.",
    status: "ANSWERED",
    createdAt: new Date("2024-10-17T11:00:00"),
    answeredAt: new Date("2024-10-17T11:20:00"),
  },
];

export const mockProductMatching = [
  {
    id: "1",
    localProductId: "prod-1",
    localProductName: "Tavuk Döner",
    platform: "Trendyol",
    platformProductId: "TRD-12345",
    platformProductName: "Tavuk Döner (500g)",
    matchStatus: "MATCHED",
    lastSynced: new Date("2024-10-19T08:00:00"),
  },
  {
    id: "2",
    localProductId: "prod-2",
    localProductName: "Köfte Menü",
    platform: "Hepsiburada",
    platformProductId: "HPB-67890",
    platformProductName: "Köfte Menü",
    matchStatus: "MATCHED",
    lastSynced: new Date("2024-10-19T08:00:00"),
  },
  {
    id: "3",
    localProductId: "prod-3",
    localProductName: "Lahmacun",
    platform: "Trendyol",
    platformProductId: null,
    platformProductName: null,
    matchStatus: "PENDING",
    lastSynced: null,
  },
  {
    id: "4",
    localProductId: "prod-4",
    localProductName: "Pide",
    platform: "N11",
    platformProductId: "N11-11111",
    platformProductName: "Pide (Orta)",
    matchStatus: "MATCHED",
    lastSynced: new Date("2024-10-18T10:00:00"),
  },
  {
    id: "5",
    localProductId: "prod-5",
    localProductName: "Ayran",
    platform: "Hepsiburada",
    platformProductId: null,
    platformProductName: null,
    matchStatus: "NOT_LISTED",
    lastSynced: null,
  },
];

