// HR Modülü Mock Data

// Maaş Bordroları
export const mockPayrolls = [
  {
    id: "1",
    employeeId: 1,
    employeeName: "Ahmet Yılmaz",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 15000,
    overtime: 2000,
    bonus: 1000,
    allowances: 500,
    grossSalary: 18500,
    tax: 2775,
    insurance: 1480,
    deductions: 0,
    netSalary: 14245,
    status: "paid",
    paymentDate: "2024-02-05",
    notes: "",
  },
  {
    id: "2",
    employeeId: 2,
    employeeName: "Ayşe Demir",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 12000,
    overtime: 1500,
    bonus: 800,
    allowances: 300,
    grossSalary: 14600,
    tax: 2190,
    insurance: 1168,
    deductions: 0,
    netSalary: 11242,
    status: "paid",
    paymentDate: "2024-02-05",
    notes: "",
  },
  {
    id: "3",
    employeeId: 3,
    employeeName: "Mehmet Kaya",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 10000,
    overtime: 1000,
    bonus: 500,
    allowances: 200,
    grossSalary: 11700,
    tax: 1755,
    insurance: 936,
    deductions: 0,
    netSalary: 9009,
    status: "paid",
    paymentDate: "2024-02-05",
    notes: "",
  },
  {
    id: "4",
    employeeId: 4,
    employeeName: "Fatma Şahin",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 8500,
    overtime: 800,
    bonus: 400,
    allowances: 150,
    grossSalary: 9850,
    tax: 1477.5,
    insurance: 788,
    deductions: 0,
    netSalary: 7584.5,
    status: "paid",
    paymentDate: "2024-02-05",
    notes: "",
  },
  {
    id: "5",
    employeeId: 5,
    employeeName: "Ali Özkan",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 8500,
    overtime: 700,
    bonus: 300,
    allowances: 100,
    grossSalary: 9600,
    tax: 1440,
    insurance: 768,
    deductions: 0,
    netSalary: 7392,
    status: "pending",
    paymentDate: null,
    notes: "",
  },
  {
    id: "6",
    employeeId: 6,
    employeeName: "Zeynep Arslan",
    period: "2024-01",
    periodLabel: "Ocak 2024",
    baseSalary: 9000,
    overtime: 0,
    bonus: 0,
    allowances: 0,
    grossSalary: 9000,
    tax: 1350,
    insurance: 720,
    deductions: 0,
    netSalary: 6930,
    status: "pending",
    paymentDate: null,
    notes: "İzinli",
  },
];

// İzin Talepleri
export const mockLeaves = [
  {
    id: "1",
    employeeId: 1,
    employeeName: "Ahmet Yılmaz",
    leaveType: "annual",
    leaveTypeLabel: "Yıllık İzin",
    startDate: "2024-03-15",
    endDate: "2024-03-20",
    days: 5,
    reason: "Tatil",
    status: "approved",
    submittedDate: "2024-02-20",
    approvedBy: "Yönetici",
    approvedDate: "2024-02-21",
    notes: "",
  },
  {
    id: "2",
    employeeId: 2,
    employeeName: "Ayşe Demir",
    leaveType: "sick",
    leaveTypeLabel: "Hastalık İzni",
    startDate: "2024-02-10",
    endDate: "2024-02-12",
    days: 2,
    reason: "Grip",
    status: "approved",
    submittedDate: "2024-02-09",
    approvedBy: "Yönetici",
    approvedDate: "2024-02-09",
    notes: "Doktor raporu eklendi",
  },
  {
    id: "3",
    employeeId: 3,
    employeeName: "Mehmet Kaya",
    leaveType: "annual",
    leaveTypeLabel: "Yıllık İzin",
    startDate: "2024-04-01",
    endDate: "2024-04-05",
    days: 4,
    reason: "Aile ziyareti",
    status: "pending",
    submittedDate: "2024-02-25",
    approvedBy: null,
    approvedDate: null,
    notes: "",
  },
  {
    id: "4",
    employeeId: 4,
    employeeName: "Fatma Şahin",
    leaveType: "unpaid",
    leaveTypeLabel: "Ücretsiz İzin",
    startDate: "2024-03-01",
    endDate: "2024-03-03",
    days: 2,
    reason: "Kişisel nedenler",
    status: "rejected",
    submittedDate: "2024-02-15",
    approvedBy: "Yönetici",
    approvedDate: "2024-02-16",
    notes: "Yoğun dönem nedeniyle reddedildi",
  },
  {
    id: "5",
    employeeId: 5,
    employeeName: "Ali Özkan",
    leaveType: "annual",
    leaveTypeLabel: "Yıllık İzin",
    startDate: "2024-05-10",
    endDate: "2024-05-15",
    days: 5,
    reason: "Tatil",
    status: "pending",
    submittedDate: "2024-02-28",
    approvedBy: null,
    approvedDate: null,
    notes: "",
  },
  {
    id: "6",
    employeeId: 6,
    employeeName: "Zeynep Arslan",
    leaveType: "maternity",
    leaveTypeLabel: "Doğum İzni",
    startDate: "2024-02-01",
    endDate: "2024-04-30",
    days: 90,
    reason: "Doğum",
    status: "approved",
    submittedDate: "2024-01-15",
    approvedBy: "Yönetici",
    approvedDate: "2024-01-16",
    notes: "Yasal izin",
  },
];

// Performans Değerlendirmeleri
export const mockPerformanceReviews = [
  {
    id: "1",
    employeeId: 1,
    employeeName: "Ahmet Yılmaz",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Genel Müdür",
    overallScore: 95,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 98,
        maxScore: 100,
        comment: "Mükemmel iş çıktıları",
      },
      {
        name: "Zaman Yönetimi",
        score: 95,
        maxScore: 100,
        comment: "Zamanında teslimat",
      },
      {
        name: "Takım Çalışması",
        score: 92,
        maxScore: 100,
        comment: "İyi takım oyuncusu",
      },
      {
        name: "İletişim",
        score: 95,
        maxScore: 100,
        comment: "Etkili iletişim",
      },
      {
        name: "Problem Çözme",
        score: 95,
        maxScore: 100,
        comment: "Yaratıcı çözümler",
      },
    ],
    strengths: [
      "Liderlik becerileri",
      "Yüksek motivasyon",
      "Müşteri odaklılık",
    ],
    improvements: ["Daha fazla delegasyon yapabilir"],
    goals: [
      "Ekip performansını %10 artırmak",
      "Yeni projeler geliştirmek",
    ],
    status: "completed",
  },
  {
    id: "2",
    employeeId: 2,
    employeeName: "Ayşe Demir",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Müdür",
    overallScore: 92,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 95,
        maxScore: 100,
        comment: "Yüksek kalite",
      },
      {
        name: "Zaman Yönetimi",
        score: 90,
        maxScore: 100,
        comment: "İyi zaman yönetimi",
      },
      {
        name: "Takım Çalışması",
        score: 93,
        maxScore: 100,
        comment: "Takımla uyumlu",
      },
      {
        name: "İletişim",
        score: 90,
        maxScore: 100,
        comment: "Açık iletişim",
      },
      {
        name: "Problem Çözme",
        score: 92,
        maxScore: 100,
        comment: "Etkili çözümler",
      },
    ],
    strengths: [
      "Teknik bilgi",
      "Detay odaklılık",
      "Güvenilirlik",
    ],
    improvements: ["Daha proaktif olabilir"],
    goals: [
      "Süreçleri optimize etmek",
      "Ekip eğitimlerine katılmak",
    ],
    status: "completed",
  },
  {
    id: "3",
    employeeId: 3,
    employeeName: "Mehmet Kaya",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Şef",
    overallScore: 88,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 90,
        maxScore: 100,
        comment: "İyi kalite",
      },
      {
        name: "Zaman Yönetimi",
        score: 85,
        maxScore: 100,
        comment: "Bazen gecikmeler",
      },
      {
        name: "Takım Çalışması",
        score: 88,
        maxScore: 100,
        comment: "Takımla uyumlu",
      },
      {
        name: "İletişim",
        score: 87,
        maxScore: 100,
        comment: "İyi iletişim",
      },
      {
        name: "Problem Çözme",
        score: 90,
        maxScore: 100,
        comment: "Yeterli",
      },
    ],
    strengths: [
      "Deneyim",
      "Sabır",
      "Uyumluluk",
    ],
    improvements: [
      "Zaman yönetimini geliştirmek",
      "Daha proaktif olmak",
    ],
    goals: [
      "Zamanında teslimat oranını artırmak",
      "Yeni teknikler öğrenmek",
    ],
    status: "completed",
  },
  {
    id: "4",
    employeeId: 4,
    employeeName: "Fatma Şahin",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Şef",
    overallScore: 90,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 92,
        maxScore: 100,
        comment: "Yüksek kalite",
      },
      {
        name: "Zaman Yönetimi",
        score: 88,
        maxScore: 100,
        comment: "İyi",
      },
      {
        name: "Takım Çalışması",
        score: 91,
        maxScore: 100,
        comment: "Mükemmel takım oyuncusu",
      },
      {
        name: "İletişim",
        score: 90,
        maxScore: 100,
        comment: "Etkili",
      },
      {
        name: "Problem Çözme",
        score: 89,
        maxScore: 100,
        comment: "Yeterli",
      },
    ],
    strengths: [
      "Müşteri ilişkileri",
      "Pozitif enerji",
      "Hızlı öğrenme",
    ],
    improvements: ["Teknik bilgiyi artırmak"],
    goals: [
      "Müşteri memnuniyetini artırmak",
      "Yeni beceriler kazanmak",
    ],
    status: "completed",
  },
  {
    id: "5",
    employeeId: 5,
    employeeName: "Ali Özkan",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Şef",
    overallScore: 85,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 87,
        maxScore: 100,
        comment: "İyi",
      },
      {
        name: "Zaman Yönetimi",
        score: 83,
        maxScore: 100,
        comment: "Geliştirilebilir",
      },
      {
        name: "Takım Çalışması",
        score: 85,
        maxScore: 100,
        comment: "Yeterli",
      },
      {
        name: "İletişim",
        score: 84,
        maxScore: 100,
        comment: "Geliştirilebilir",
      },
      {
        name: "Problem Çözme",
        score: 86,
        maxScore: 100,
        comment: "İyi",
      },
    ],
    strengths: [
      "Çalışkanlık",
      "Uyumluluk",
    ],
    improvements: [
      "İletişim becerilerini geliştirmek",
      "Zaman yönetimi",
    ],
    goals: [
      "Performansı artırmak",
      "Ekip ile daha iyi iletişim kurmak",
    ],
    status: "completed",
  },
  {
    id: "6",
    employeeId: 6,
    employeeName: "Zeynep Arslan",
    reviewPeriod: "2024-Q1",
    reviewPeriodLabel: "2024 Q1",
    reviewDate: "2024-04-01",
    reviewer: "Müdür",
    overallScore: 93,
    criteria: [
      {
        name: "İş Kalitesi",
        score: 95,
        maxScore: 100,
        comment: "Mükemmel",
      },
      {
        name: "Zaman Yönetimi",
        score: 92,
        maxScore: 100,
        comment: "Çok iyi",
      },
      {
        name: "Takım Çalışması",
        score: 93,
        maxScore: 100,
        comment: "Harika",
      },
      {
        name: "İletişim",
        score: 94,
        maxScore: 100,
        comment: "Mükemmel",
      },
      {
        name: "Problem Çözme",
        score: 92,
        maxScore: 100,
        comment: "İyi",
      },
    ],
    strengths: [
      "Detay odaklılık",
      "Hızlı öğrenme",
      "Müşteri memnuniyeti",
    ],
    improvements: ["Daha fazla inisiyatif alabilir"],
    goals: [
      "Kariyer gelişimi",
      "Liderlik becerilerini geliştirmek",
    ],
    status: "completed",
  },
];

// Eğitim Kayıtları
export const mockTrainings = [
  {
    id: "1",
    title: "Müşteri Hizmetleri Eğitimi",
    description: "Müşteri memnuniyetini artırmak için eğitim programı",
    trainer: "Dış Eğitmen",
    category: "soft-skills",
    categoryLabel: "Yumuşak Beceriler",
    startDate: "2024-03-15",
    endDate: "2024-03-16",
    duration: 2,
    location: "Ofis",
    maxParticipants: 20,
    participants: [
      { employeeId: 4, employeeName: "Fatma Şahin", status: "completed", score: 95 },
      { employeeId: 5, employeeName: "Ali Özkan", status: "completed", score: 88 },
      { employeeId: 6, employeeName: "Zeynep Arslan", status: "completed", score: 92 },
    ],
    status: "completed",
    cost: 5000,
    materials: ["Sunum", "Video", "Sertifika"],
  },
  {
    id: "2",
    title: "Gıda Güvenliği Eğitimi",
    description: "Gıda güvenliği standartları ve uygulamaları",
    trainer: "İç Eğitmen",
    category: "compliance",
    categoryLabel: "Uyumluluk",
    startDate: "2024-04-01",
    endDate: "2024-04-01",
    duration: 1,
    location: "Ofis",
    maxParticipants: 15,
    participants: [
      { employeeId: 2, employeeName: "Ayşe Demir", status: "registered", score: null },
      { employeeId: 3, employeeName: "Mehmet Kaya", status: "registered", score: null },
    ],
    status: "scheduled",
    cost: 2000,
    materials: ["Sunum", "Dokümantasyon"],
  },
  {
    id: "3",
    title: "Liderlik ve Yönetim",
    description: "Yöneticiler için liderlik becerileri geliştirme",
    trainer: "Dış Eğitmen",
    category: "leadership",
    categoryLabel: "Liderlik",
    startDate: "2024-05-10",
    endDate: "2024-05-12",
    duration: 3,
    location: "Dış Mekan",
    maxParticipants: 10,
    participants: [
      { employeeId: 1, employeeName: "Ahmet Yılmaz", status: "registered", score: null },
    ],
    status: "scheduled",
    cost: 15000,
    materials: ["Kitap", "Sunum", "Workshop"],
  },
  {
    id: "4",
    title: "Muhasebe Temelleri",
    description: "Temel muhasebe bilgileri ve uygulamaları",
    trainer: "İç Eğitmen",
    category: "technical",
    categoryLabel: "Teknik",
    startDate: "2024-02-20",
    endDate: "2024-02-22",
    duration: 3,
    location: "Ofis",
    maxParticipants: 12,
    participants: [
      { employeeId: 6, employeeName: "Zeynep Arslan", status: "completed", score: 90 },
    ],
    status: "completed",
    cost: 3000,
    materials: ["Sunum", "Örnekler", "Sertifika"],
  },
  {
    id: "5",
    title: "Dijital Pazarlama",
    description: "Sosyal medya ve dijital pazarlama stratejileri",
    trainer: "Dış Eğitmen",
    category: "marketing",
    categoryLabel: "Pazarlama",
    startDate: "2024-06-01",
    endDate: "2024-06-02",
    duration: 2,
    location: "Online",
    maxParticipants: 25,
    participants: [],
    status: "planned",
    cost: 8000,
    materials: ["Video", "Sunum", "Araçlar"],
  },
];

