// Mock data for Products modules

// Unsplash image URLs for products
const unsplashImages = {
  doner: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=400&fit=crop",
  kofte: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=400&fit=crop",
  lahmacun: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop",
  pide: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=400&fit=crop",
  ayran: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=400&fit=crop",
  kebab: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=400&fit=crop",
  menu: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=400&fit=crop",
  drink: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=400&fit=crop",
  dessert: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=400&fit=crop",
  warehouse: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&h=400&fit=crop",
};

export const mockProducts = [
  {
    id: "1",
    productCode: "TD-DRM-001",
    name: "Tavuk Döner Dürüm",
    shortDescription: "Taze tavuk döner, özel baharatlarla marine edilmiş",
    price: 45.0,
    comparePrice: 50.0,
    costPrice: 25.0,
    stock: 25,
    category: "1-1",
    categoryName: "Dönerler",
    images: [unsplashImages.doner],
    thumbnail: unsplashImages.doner,
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "2",
    productCode: "KFT-MNU-002",
    name: "Köfte Menü",
    shortDescription: "Izgara köfte, pilav, salata ve ayran",
    price: 65.0,
    comparePrice: 70.0,
    costPrice: 35.0,
    stock: 18,
    category: "1-2",
    categoryName: "Kebaplar",
    images: [unsplashImages.kofte],
    thumbnail: unsplashImages.kofte,
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: "3",
    productCode: "AYR-001",
    name: "Ayran",
    shortDescription: "Ev yapımı taze ayran",
    price: 8.0,
    comparePrice: 10.0,
    costPrice: 3.0,
    stock: 150,
    category: "3-1",
    categoryName: "Soğuk İçecekler",
    images: [unsplashImages.ayran],
    thumbnail: unsplashImages.ayran,
    isActive: true,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "4",
    productCode: "LHM-001",
    name: "Lahmacun",
    shortDescription: "İnce hamur üzerine özel harç ile hazırlanmış",
    price: 12.0,
    comparePrice: 15.0,
    costPrice: 5.0,
    stock: 50,
    category: "1-3",
    categoryName: "Pideler",
    images: [unsplashImages.lahmacun],
    thumbnail: unsplashImages.lahmacun,
    isActive: true,
    isFeatured: false,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: "5",
    productCode: "PD-001",
    name: "Karışık Pide",
    shortDescription: "Kaşar, sucuk, yumurta ve pastırma ile",
    price: 35.0,
    comparePrice: 40.0,
    costPrice: 18.0,
    stock: 30,
    category: "1-3",
    categoryName: "Pideler",
    images: [unsplashImages.pide],
    thumbnail: unsplashImages.pide,
    isActive: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "6",
    productCode: "KB-001",
    name: "Adana Kebap",
    shortDescription: "Acılı kıyma ile hazırlanmış özel kebap",
    price: 55.0,
    comparePrice: 60.0,
    costPrice: 30.0,
    stock: 20,
    category: "1-2",
    categoryName: "Kebaplar",
    images: [unsplashImages.kebab],
    thumbnail: unsplashImages.kebab,
    isActive: true,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 203,
  },
];

export const mockWarehouses = [
  {
    id: "1",
    name: "Ana Depo",
    address: "İstanbul, Kadıköy",
    capacity: 1000,
    currentStock: 750,
    manager: "Ahmet Yılmaz",
    phone: "+90 555 123 4567",
    isActive: true,
  },
  {
    id: "2",
    name: "Soğuk Hava Deposu",
    address: "İstanbul, Ümraniye",
    capacity: 500,
    currentStock: 320,
    manager: "Mehmet Kaya",
    phone: "+90 555 234 5678",
    isActive: true,
  },
  {
    id: "3",
    name: "Yedek Depo",
    address: "İstanbul, Bakırköy",
    capacity: 300,
    currentStock: 150,
    manager: "Ayşe Demir",
    phone: "+90 555 345 6789",
    isActive: true,
  },
];

export const mockProduction = [
  {
    id: "1",
    productName: "Tavuk Döner",
    quantity: 50,
    unit: "kg",
    recipe: "Tavuk Döner Reçetesi",
    startDate: new Date("2024-10-19T08:00:00"),
    endDate: new Date("2024-10-19T12:00:00"),
    status: "COMPLETED",
    cost: 1250.0,
  },
  {
    id: "2",
    productName: "Köfte",
    quantity: 30,
    unit: "kg",
    recipe: "Köfte Reçetesi",
    startDate: new Date("2024-10-19T09:00:00"),
    endDate: new Date("2024-10-19T11:00:00"),
    status: "IN_PROGRESS",
    cost: 900.0,
  },
  {
    id: "3",
    productName: "Lahmacun",
    quantity: 200,
    unit: "adet",
    recipe: "Lahmacun Reçetesi",
    startDate: new Date("2024-10-18T07:00:00"),
    endDate: new Date("2024-10-18T10:00:00"),
    status: "COMPLETED",
    cost: 600.0,
  },
  {
    id: "4",
    productName: "Pide",
    quantity: 100,
    unit: "adet",
    recipe: "Pide Reçetesi",
    startDate: new Date("2024-10-18T08:00:00"),
    endDate: new Date("2024-10-18T11:00:00"),
    status: "COMPLETED",
    cost: 800.0,
  },
  {
    id: "5",
    productName: "Ayran",
    quantity: 500,
    unit: "lt",
    recipe: "Ayran Reçetesi",
    startDate: new Date("2024-10-19T06:00:00"),
    endDate: new Date("2024-10-19T08:00:00"),
    status: "COMPLETED",
    cost: 400.0,
  },
];

export const mockPriceLists = [
  {
    id: "1",
    name: "VIP Müşteri Fiyat Listesi",
    description: "VIP müşteriler için özel fiyatlandırma",
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-12-31"),
    customerGroup: "VIP",
    discountRate: 10,
    isActive: true,
    productCount: 25,
  },
  {
    id: "2",
    name: "Toplu Alım Fiyat Listesi",
    description: "100 adet üzeri alımlar için",
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-12-31"),
    customerGroup: "BULK",
    discountRate: 15,
    isActive: true,
    productCount: 30,
  },
  {
    id: "3",
    name: "Yeni Müşteri Fiyat Listesi",
    description: "İlk siparişler için özel fiyat",
    validFrom: new Date("2024-10-01"),
    validUntil: new Date("2024-12-31"),
    customerGroup: "NEW",
    discountRate: 5,
    isActive: true,
    productCount: 20,
  },
  {
    id: "4",
    name: "Kurumsal Fiyat Listesi",
    description: "Kurumsal müşteriler için",
    validFrom: new Date("2024-01-01"),
    validUntil: new Date("2024-12-31"),
    customerGroup: "CORPORATE",
    discountRate: 12,
    isActive: true,
    productCount: 35,
  },
  {
    id: "5",
    name: "Sezonluk İndirim",
    description: "Yıl sonu indirim kampanyası",
    validFrom: new Date("2024-12-01"),
    validUntil: new Date("2024-12-31"),
    customerGroup: "ALL",
    discountRate: 20,
    isActive: false,
    productCount: 40,
  },
];

export const mockCatalogs = [
  {
    id: "1",
    name: "2024 Kış Kataloğu",
    description: "Kış sezonu ürün kataloğu",
    productCount: 45,
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-10-15"),
    isPublished: true,
    pdfUrl: "/catalogs/2024-kis.pdf",
    shareUrl: "https://civardaki.com/catalog/2024-kis",
  },
  {
    id: "2",
    name: "Özel Menü Kataloğu",
    description: "Özel menü öğeleri",
    productCount: 20,
    createdAt: new Date("2024-09-15"),
    updatedAt: new Date("2024-10-10"),
    isPublished: true,
    pdfUrl: "/catalogs/ozel-menu.pdf",
    shareUrl: "https://civardaki.com/catalog/ozel-menu",
  },
  {
    id: "3",
    name: "Tatil Kataloğu",
    description: "Tatil dönemi özel ürünler",
    productCount: 15,
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-05"),
    isPublished: false,
    pdfUrl: null,
    shareUrl: null,
  },
];

