// Mock data for Suppliers
export const mockSuppliers = [
    {
        id: "1",
        name: "Taze Et Ticaret Ltd.",
        category: "Gıda / Et",
        contactPerson: "Mehmet Yılmaz",
        phone: "+90 212 555 0123",
        email: "info@tazeet.com",
        address: "Merkez Mah. Kasap Sk. No:12, Kağıthane, İstanbul",
        rating: 4.8,
        status: "active",
        totalPurchases: 124500,
        activeOrders: 2,
        outstandingBalance: 12450.50,
        reliability: 98, // %
        tags: ["Güvenilir", "A Kalite", "Hızlı Teslimat"],
        lastPurchaseDate: "2024-01-15",
        logo: "https://ui-avatars.com/api/?name=Taze+Et&background=0D8ABC&color=fff",
        notes: "Haftalık taze sevkiyat yapar. Ödemeler genelde 30 gün valörlü.",
    },
    {
        id: "2",
        name: "Süt Ürünleri A.Ş.",
        category: "Gıda / Süt",
        contactPerson: "Fatma Kaya",
        phone: "+90 216 555 0234",
        email: "info@suturunleri.com",
        address: "Organize Sanayi Bölgesi, 2. Cadde, Gebze",
        rating: 4.5,
        status: "active",
        totalPurchases: 85200,
        activeOrders: 1,
        outstandingBalance: 5200.00,
        reliability: 95,
        tags: ["Endüstriyel", "Sertifikalı"],
        lastPurchaseDate: "2024-01-12",
        logo: "https://ui-avatars.com/api/?name=Sut+As&background=10b981&color=fff",
        notes: "Yoğurt ve peynir grubunda ana tedarikçi.",
    },
    {
        id: "3",
        name: "Sebze Meyve Toptan",
        category: "Gıda / Sebze",
        contactPerson: "Ali Özkan",
        phone: "+90 216 555 0345",
        email: "info@sebzemeyve.com",
        address: "Bayrampaşa Hal Kompleksi, No:45, İstanbul",
        rating: 3.9,
        status: "active",
        totalPurchases: 45600,
        activeOrders: 0,
        outstandingBalance: 0,
        reliability: 82,
        tags: ["Hızlı Tüketim", "Değişken Fiyat"],
        lastPurchaseDate: "2024-01-10",
        logo: "https://ui-avatars.com/api/?name=Sebze+Meyve&background=f59e0b&color=fff",
        notes: "Fiyatlar günlük değişir. Teslimat saatlerine dikkat edilmeli.",
    },
    {
        id: "4",
        name: "Ambalaj Dünyası",
        category: "Lojistik / Ambalaj",
        contactPerson: "Canan Altın",
        phone: "+90 212 555 0456",
        email: "canan@ambalajdunyasi.com",
        address: "İkitelli OSB, Ambalajcılar Sitesi, No:7",
        rating: 4.9,
        status: "inactive",
        totalPurchases: 12000,
        activeOrders: 0,
        outstandingBalance: 0,
        reliability: 99,
        tags: ["Ekolojik", "Özel Baskı"],
        lastPurchaseDate: "2023-12-15",
        logo: "https://ui-avatars.com/api/?name=Ambalaj&background=6366f1&color=fff",
        notes: "Baskılı poşet ve kutu tedarikçisi. Şu an çalışılmıyor.",
    }
];

export const supplierStats = {
    totalSuppliers: 4,
    activePartners: 3,
    totalSpend: 267300,
    pendingQuotes: 5,
    avgReliability: 93.5,
};
