// Mock data for user orders

export const mockOrders = [
  {
    id: "ord-1",
    businessId: "1",
    businessName: "Lezzet Dönercisi",
    businessLogo: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=200&h=200&fit=crop",
    orderDate: new Date("2024-10-19T14:30:00"),
    status: "completed", // pending, confirmed, preparing, on_the_way, delivered, completed, cancelled
    items: [
      {
        id: "item-1",
        productId: "p1",
        productName: "Tavuk Döner Dürüm",
        quantity: 2,
        price: 45.0,
        variant: { name: "Boy", value: "Orta" },
        total: 90.0,
      },
      {
        id: "item-2",
        productId: "p2",
        productName: "Köfte Menü",
        quantity: 1,
        price: 65.0,
        variant: null,
        total: 65.0,
      },
    ],
    subtotal: 155.0,
    deliveryFee: 10.0,
    total: 165.0,
    paymentMethod: "cash", // cash, online
    paymentStatus: "paid", // paid, pending, refunded
    deliveryAddress: "Bağdat Caddesi No:123, Daire:5, Kadıköy, İstanbul",
    deliveryNote: "Kapı zili çalın",
    deliveryType: "hand", // hand, cargo
    trackingNumber: null,
    estimatedDelivery: new Date("2024-10-19T15:30:00"),
    actualDelivery: new Date("2024-10-19T15:25:00"),
    rating: 5,
    review: "Çok hızlı ve lezzetli, teşekkürler!",
  },
  {
    id: "ord-2",
    businessId: "2",
    businessName: "Kadıköy Market",
    businessLogo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&h=200&fit=crop",
    orderDate: new Date("2024-10-18T10:15:00"),
    status: "on_the_way",
    items: [
      {
        id: "item-3",
        productId: "p3",
        productName: "Taze Domates",
        quantity: 2,
        price: 15.0,
        variant: { name: "Miktar", value: "1kg" },
        total: 30.0,
      },
    ],
    subtotal: 30.0,
    deliveryFee: 5.0,
    total: 35.0,
    paymentMethod: "online",
    paymentStatus: "paid",
    deliveryAddress: "Moda Caddesi No:45, Daire:12, Kadıköy, İstanbul",
    deliveryNote: "",
    deliveryType: "hand",
    trackingNumber: null,
    estimatedDelivery: new Date("2024-10-18T11:00:00"),
    actualDelivery: null,
    rating: null,
    review: null,
  },
  {
    id: "ord-3",
    businessId: "1",
    businessName: "Lezzet Dönercisi",
    businessLogo: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=200&h=200&fit=crop",
    orderDate: new Date("2024-10-17T19:45:00"),
    status: "preparing",
    items: [
      {
        id: "item-4",
        productId: "p1",
        productName: "Tavuk Döner Dürüm",
        quantity: 1,
        price: 45.0,
        variant: { name: "Boy", value: "Büyük" },
        total: 55.0,
      },
    ],
    subtotal: 55.0,
    deliveryFee: 10.0,
    total: 65.0,
    paymentMethod: "cash",
    paymentStatus: "pending",
    deliveryAddress: "Fenerbahçe Mahallesi, Sokak No:7, Kadıköy, İstanbul",
    deliveryNote: "",
    deliveryType: "hand",
    trackingNumber: null,
    estimatedDelivery: new Date("2024-10-17T20:30:00"),
    actualDelivery: null,
    rating: null,
    review: null,
  },
  {
    id: "ord-4",
    businessId: "2",
    businessName: "Kadıköy Market",
    businessLogo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&h=200&fit=crop",
    orderDate: new Date("2024-10-15T08:00:00"),
    status: "completed",
    items: [
      {
        id: "item-5",
        productId: "p3",
        productName: "Taze Domates",
        quantity: 5,
        price: 15.0,
        variant: { name: "Miktar", value: "1kg" },
        total: 75.0,
      },
    ],
    subtotal: 75.0,
    deliveryFee: 5.0,
    total: 80.0,
    paymentMethod: "online",
    paymentStatus: "paid",
    deliveryAddress: "Acıbadem Mahallesi, Caddesi No:23, Kadıköy, İstanbul",
    deliveryNote: "",
    deliveryType: "cargo",
    trackingNumber: "KGO123456789",
    estimatedDelivery: new Date("2024-10-16T18:00:00"),
    actualDelivery: new Date("2024-10-16T17:45:00"),
    rating: 4,
    review: "İyi paketlenmiş, taze ürünler",
  },
  {
    id: "ord-5",
    businessId: "1",
    businessName: "Lezzet Dönercisi",
    businessLogo: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=200&h=200&fit=crop",
    orderDate: new Date("2024-10-14T12:00:00"),
    status: "cancelled",
    items: [
      {
        id: "item-6",
        productId: "p2",
        productName: "Köfte Menü",
        quantity: 1,
        price: 65.0,
        variant: null,
        total: 65.0,
      },
    ],
    subtotal: 65.0,
    deliveryFee: 10.0,
    total: 75.0,
    paymentMethod: "online",
    paymentStatus: "refunded",
    deliveryAddress: "Bahariye Caddesi No:56, Kadıköy, İstanbul",
    deliveryNote: "",
    deliveryType: "hand",
    trackingNumber: null,
    estimatedDelivery: new Date("2024-10-14T13:00:00"),
    actualDelivery: null,
    cancellationReason: "Stokta yok",
    rating: null,
    review: null,
  },
];

export function getOrderStatusText(status) {
  const statusMap = {
    pending: "Beklemede",
    confirmed: "Onaylandı",
    preparing: "Hazırlanıyor",
    on_the_way: "Yolda",
    delivered: "Teslim Edildi",
    completed: "Tamamlandı",
    cancelled: "İptal Edildi",
  };
  return statusMap[status] || status;
}

export function getOrderStatusColor(status) {
  const colorMap = {
    pending: "yellow",
    confirmed: "blue",
    preparing: "purple",
    on_the_way: "indigo",
    delivered: "green",
    completed: "green",
    cancelled: "red",
  };
  return colorMap[status] || "gray";
}

