const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

function slugifyTR(text) {
  return text
    .toString()
    .toLowerCase("tr-TR")
    .replace(/ğ/g, "g")
    .replace(/ü/g, "u")
    .replace(/ş/g, "s")
    .replace(/ı/g, "i")
    .replace(/ö/g, "o")
    .replace(/ç/g, "c")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

const categoryTree = [
  {
    name: "Yeme İçme",
    icon: "UtensilsCrossed",
    color: "#ef4444",
    description: "Restoranlar, kafeler, tatlıcılar ve yeme içme işletmeleri.",
    keywords: "restoran,kafe,pastane,firin,doner,kebap,pizza,burger,yemek,icecek",
    featured: true,
    children: [
      "Restoran",
      "Lokanta",
      "Kebapçı",
      "Dönerci",
      "Pideci",
      "Lahmacuncu",
      "Ev Yemekleri",
      "Balık Restoranı",
      "Et Restoranı",
      "Kafe",
      "Kahve Dükkanı",
      "Pastane",
      "Fırın",
      "Tatlıcı",
      "Baklavacı",
      "Dondurmacı",
      "Fast Food",
      "Burgerci",
      "Pizzacı",
      "Çiğköfteci",
      "Büfe",
      "Nargile Kafe",
      "Meyhane",
      "Bar",
      "Gece Kulübü",
      "Kahvaltı Salonu",
      "Catering",
      "Toplu Yemek",
      "Paket Servis Mutfağı",
      "Waffle & Krep",
    ],
  },
  {
    name: "Market & Perakende",
    icon: "ShoppingBasket",
    color: "#22c55e",
    description: "Günlük ihtiyaç, perakende satış ve mağaza işletmeleri.",
    keywords: "market,bakkal,manav,kuruyemis,kirtasiye,petshop,tekel,hediyelik",
    featured: true,
    children: [
      "Market",
      "Süpermarket",
      "Bakkal",
      "Şarküteri",
      "Manav",
      "Kuruyemişçi",
      "Kasap Şarküteri",
      "Tekel Bayi",
      "Su Bayi",
      "Petshop",
      "Kırtasiye",
      "Kitapçı",
      "Oyuncakçı",
      "Bijuteri",
      "Hediyelik Eşya",
      "Züccaciye",
      "Saatçi",
      "Tütüncü",
      "Organik Ürünler",
      "Bebek Ürünleri",
    ],
  },
  {
    name: "Güzellik & Bakım",
    icon: "Scissors",
    color: "#ec4899",
    description: "Kişisel bakım, güzellik ve estetik hizmetleri.",
    keywords: "kuafor,berber,guzellik,nail,lazer,epilasyon,makyaj,spa,masaj",
    featured: true,
    children: [
      "Kadın Kuaförü",
      "Erkek Kuaförü",
      "Berber",
      "Güzellik Merkezi",
      "Cilt Bakımı",
      "Lazer Epilasyon",
      "Nail Studio",
      "Makyaj Stüdyosu",
      "Masaj Salonu",
      "SPA Merkezi",
      "Kalıcı Makyaj",
      "Dövme Stüdyosu",
      "Solaryum",
      "Saç Ekim Merkezi",
      "Estetik Kliniği",
    ],
  },
  {
    name: "Sağlık",
    icon: "HeartPulse",
    color: "#06b6d4",
    description: "Sağlık, klinik, terapi ve medikal hizmetler.",
    keywords: "saglik,eczane,dis,psikolog,diyetisyen,fizyoterapi,optik,medikal,veteriner",
    featured: true,
    children: [
      "Eczane",
      "Diş Hekimi",
      "Diş Kliniği",
      "Özel Klinik",
      "Poliklinik",
      "Psikolog",
      "Psikiyatrist",
      "Diyetisyen",
      "Fizyoterapist",
      "Veteriner",
      "Optik",
      "İşitme Merkezi",
      "Medikal Ürünler",
      "Evde Sağlık Hizmeti",
      "Laboratuvar",
      "Radyoloji Merkezi",
    ],
  },
  {
    name: "Ev Hizmetleri",
    icon: "House",
    color: "#3b82f6",
    description: "Ev, ofis ve yaşam alanlarına yönelik hizmetler.",
    keywords: "temizlik,nakliyat,elektrikci,tesisatci,kombi,klima,cilingir,montaj",
    featured: true,
    children: [
      "Temizlik Şirketi",
      "Ofis Temizliği",
      "Halı Yıkama",
      "Koltuk Yıkama",
      "İlaçlama",
      "Evden Eve Nakliyat",
      "Parça Eşya Taşıma",
      "Su Tesisatçısı",
      "Elektrikçi",
      "Kombi Servisi",
      "Klima Servisi",
      "Beyaz Eşya Servisi",
      "Boya Badana",
      "Alçıpan Ustası",
      "Çilingir",
      "Cam Balkon",
      "Perde & Stor",
      "Mobilya Montaj",
      "Parke Ustası",
      "Doğalgaz Tesisatı",
    ],
  },
  {
    name: "İnşaat & Tadilat",
    icon: "Hammer",
    color: "#f59e0b",
    description: "İnşaat, tadilat, yapı ve dekorasyon hizmetleri.",
    keywords: "insaat,tadilat,mimar,dekorasyon,marangoz,pvc,demir,cati",
    featured: true,
    children: [
      "Müteahhit",
      "İnşaat Firması",
      "Mimar",
      "İç Mimar",
      "Dekorasyon Firması",
      "Seramik & Fayans",
      "Marangoz",
      "Demir Doğrama",
      "PVC Doğrama",
      "Alüminyum Doğrama",
      "Çatı Sistemleri",
      "Mantolama",
      "İskele",
      "Asma Tavan",
      "Mermer & Granit",
      "Asansör Hizmetleri",
      "Isı Yalıtımı",
      "Su Yalıtımı",
    ],
  },
  {
    name: "Otomotiv",
    icon: "Car",
    color: "#64748b",
    description: "Araç bakım, satış, temizlik ve destek hizmetleri.",
    keywords: "oto,lastik,kaporta,ekspertiz,cekici,galeri,kiralama,yedek parca",
    featured: true,
    children: [
      "Oto Tamir",
      "Oto Elektrik",
      "Kaporta Boya",
      "Lastikçi",
      "Oto Yıkama",
      "Oto Kuaför",
      "Ekspertiz",
      "Yedek Parça",
      "Araç Kiralama",
      "Çekici",
      "Akücü",
      "Cam Filmi & PPF",
      "LPG Dönüşüm",
      "Oto Döşeme",
      "Motosiklet Servisi",
      "Oto Galeri",
    ],
  },
  {
    name: "Teknoloji & Yazılım",
    icon: "Laptop",
    color: "#6366f1",
    description: "Yazılım, tasarım, dijital pazarlama ve teknoloji hizmetleri.",
    keywords: "yazilim,web tasarim,mobil uygulama,seo,sosyal medya,telefon tamiri,teknik servis",
    featured: true,
    children: [
      "Web Tasarım",
      "Yazılım Geliştirme",
      "Mobil Uygulama",
      "E-Ticaret Çözümleri",
      "SEO",
      "Google Ads Yönetimi",
      "Meta Reklam Yönetimi",
      "Sosyal Medya Yönetimi",
      "Grafik Tasarım",
      "Kurumsal Kimlik Tasarımı",
      "Bilgisayar Teknik Servis",
      "Telefon Tamiri",
      "Tablet Tamiri",
      "Güvenlik Kamerası",
      "Alarm Sistemleri",
      "Network & Sunucu",
      "Yazıcı & Ofis Donanımı",
      "Domain & Hosting",
    ],
  },
  {
    name: "Eğitim & Danışmanlık",
    icon: "GraduationCap",
    color: "#8b5cf6",
    description: "Kurslar, özel dersler ve profesyonel danışmanlık hizmetleri.",
    keywords: "egitim,kurs,ozel ders,danismanlik,koçluk,surucu kursu,yabanci dil",
    featured: true,
    children: [
      "Kurs Merkezi",
      "Özel Ders",
      "Yabancı Dil Kursu",
      "Sürücü Kursu",
      "YKS Hazırlık",
      "LGS Hazırlık",
      "Yazılım Eğitimi",
      "Müzik Kursu",
      "Dans Kursu",
      "Sanat Atölyesi",
      "Koçluk",
      "Kurumsal Danışmanlık",
      "Eğitim Danışmanlığı",
      "Muhasebe Danışmanlığı",
      "İK Danışmanlığı",
    ],
  },
  {
    name: "Hukuk & Finans",
    icon: "Scale",
    color: "#0f172a",
    description: "Hukuki, mali ve finansal danışmanlık hizmetleri.",
    keywords: "avukat,muhasebe,sigorta,finans,mali musavir,hukuk",
    featured: true,
    children: [
      "Avukat",
      "Hukuk Bürosu",
      "Mali Müşavir",
      "Muhasebeci",
      "Sigorta Acentesi",
      "Finans Danışmanı",
      "Kredi Danışmanlığı",
      "Vergi Danışmanlığı",
      "İcra & Arabuluculuk",
    ],
  },
  {
    name: "Emlak",
    icon: "Building2",
    color: "#14b8a6",
    description: "Gayrimenkul, satış, kiralama ve danışmanlık hizmetleri.",
    keywords: "emlak,konut,arsa,ofis,gayrimenkul,kiralik,satilik",
    featured: true,
    children: [
      "Emlak Ofisi",
      "Gayrimenkul Danışmanı",
      "Konut Projesi",
      "Arsa Ofisi",
      "Ticari Gayrimenkul",
      "Kiralık Daire",
      "Satılık Daire",
    ],
  },
  {
    name: "Turizm & Konaklama",
    icon: "Hotel",
    color: "#0ea5e9",
    description: "Konaklama, seyahat ve turizm çözümleri.",
    keywords: "otel,pansiyon,apart,seyahat,tur,transfer",
    featured: false,
    children: [
      "Otel",
      "Pansiyon",
      "Butik Otel",
      "Apart Otel",
      "Günlük Kiralık",
      "Seyahat Acentesi",
      "Tur Şirketi",
      "Transfer Hizmeti",
      "Araçlı Tur",
    ],
  },
  {
    name: "Spor & Fitness",
    icon: "Dumbbell",
    color: "#84cc16",
    description: "Spor, antrenman ve sağlıklı yaşam hizmetleri.",
    keywords: "spor,fitness,pilates,yoga,yuzme,antrenor",
    featured: false,
    children: [
      "Spor Salonu",
      "Pilates",
      "Yoga",
      "Yüzme Kursu",
      "Futbol Okulu",
      "Basketbol Okulu",
      "Kişisel Antrenör",
      "Beslenme Koçluğu",
      "Crossfit",
      "Dövüş Sporları",
    ],
  },
  {
    name: "Evcil Hayvan",
    icon: "PawPrint",
    color: "#f97316",
    description: "Evcil hayvan bakım, satış ve destek hizmetleri.",
    keywords: "petshop,veteriner,mama,pet kuafor,pet oteli",
    featured: false,
    children: [
      "Petshop",
      "Pet Kuaför",
      "Pet Oteli",
      "Evcil Hayvan Eğitimi",
      "Mama & Aksesuar",
      "Pet Veteriner",
    ],
  },
  {
    name: "Organizasyon & Etkinlik",
    icon: "PartyPopper",
    color: "#e11d48",
    description: "Düğün, etkinlik ve organizasyon hizmetleri.",
    keywords: "organizasyon,dugun,dogum gunu,video,fotograf,ses,isik",
    featured: false,
    children: [
      "Düğün Organizasyonu",
      "Nişan & Kına Organizasyonu",
      "Doğum Günü Organizasyonu",
      "Baby Shower Organizasyonu",
      "Ajans",
      "Fotoğrafçı",
      "Düğün Fotoğrafçısı",
      "Video Prodüksiyon",
      "Ses Işık Sistemleri",
      "DJ & Müzik",
      "Davetiye & Baskı",
      "Çiçekçi",
      "Nikah Şekeri & Süsleme",
    ],
  },
  {
    name: "Tekstil & Moda",
    icon: "Shirt",
    color: "#7c3aed",
    description: "Giyim, tekstil ve moda odaklı işletmeler.",
    keywords: "tekstil,giyim,butik,terzi,ayakkabi,canta",
    featured: false,
    children: [
      "Butik",
      "Giyim Mağazası",
      "Terzi",
      "Abiye",
      "Ayakkabı",
      "Çanta",
      "Tesettür Giyim",
      "Çocuk Giyim",
      "İç Giyim",
      "Spor Giyim",
      "Kumaşçı",
    ],
  },
  {
    name: "Sanayi & Üretim",
    icon: "Factory",
    color: "#475569",
    description: "İmalat, üretim ve endüstriyel işletmeler.",
    keywords: "sanayi,uretim,makine,metal,ambalaj,cnc",
    featured: false,
    children: [
      "Makine İmalatı",
      "Metal İşleme",
      "Plastik Üretim",
      "Ahşap Üretim",
      "Ambalaj",
      "Endüstriyel Bakım",
      "Kaynak Hizmetleri",
      "CNC İşleme",
    ],
  },
  {
    name: "Tarım & Hayvancılık",
    icon: "Tractor",
    color: "#65a30d",
    description: "Tarım, sulama, yem ve kırsal üretim hizmetleri.",
    keywords: "tarim,hayvancilik,sulama,tohum,gubre,yem",
    featured: false,
    children: [
      "Tarım Ekipmanları",
      "Tohum & Gübre",
      "Sulama Sistemleri",
      "Hayvancılık Ürünleri",
      "Yem Bayii",
      "Seracılık",
      "Fidan & Peyzaj Bitkileri",
      "Arıcılık Ürünleri",
    ],
  },
  {
    name: "Nakliye & Lojistik",
    icon: "Truck",
    color: "#334155",
    description: "Taşıma, depolama ve lojistik çözümleri.",
    keywords: "nakliye,lojistik,kargo,kurye,depolama",
    featured: false,
    children: [
      "Kargo",
      "Kurye",
      "Moto Kurye",
      "Lojistik Firma",
      "Depolama",
      "Soğuk Zincir Taşımacılık",
      "Parsiyel Taşımacılık",
      "Uluslararası Taşımacılık",
    ],
  },
  {
    name: "Diğer Profesyonel Hizmetler",
    icon: "Briefcase",
    color: "#6b7280",
    description: "Diğer uzmanlık ve destek hizmetleri.",
    keywords: "matbaa,tabela,reklam,drone,guvenlik,tercume",
    featured: false,
    children: [
      "Matbaa",
      "Tabela",
      "Reklam Ajansı",
      "Tercüme Bürosu",
      "Çağrı Merkezi Hizmeti",
      "Güvenlik Sistemleri",
      "İş Güvenliği",
      "Drone Hizmeti",
      "Fotoğraf Stüdyosu",
      "İnsan Kaynakları Hizmeti",
      "Fuar Stand Hizmetleri",
      "Diğer",
    ],
  },
];

async function upsertParentCategory(parentData, index) {
  const parentSlug = slugifyTR(parentData.name);

  return prisma.category.upsert({
    where: { slug: parentSlug },
    update: {
      name: parentData.name,
      description: parentData.description || null,
      icon: parentData.icon || null,
      color: parentData.color || null,
      level: 0,
      path: parentSlug,
      sortOrder: index,
      isActive: true,
      isFeatured: !!parentData.featured,
      keywords: parentData.keywords || null,
    },
    create: {
      name: parentData.name,
      slug: parentSlug,
      description: parentData.description || null,
      icon: parentData.icon || null,
      color: parentData.color || null,
      level: 0,
      path: parentSlug,
      sortOrder: index,
      isActive: true,
      isFeatured: !!parentData.featured,
      keywords: parentData.keywords || null,
    },
  });
}

async function upsertChildCategory(parent, childName, index) {
  const rawChildSlug = slugifyTR(childName);
  const uniqueChildSlug = `${parent.slug}-${rawChildSlug}`;

  return prisma.category.upsert({
    where: { slug: uniqueChildSlug },
    update: {
      name: childName,
      parentId: parent.id,
      level: 1,
      path: `${parent.slug}/${rawChildSlug}`,
      sortOrder: index,
      isActive: true,
      isFeatured: false,
    },
    create: {
      name: childName,
      slug: uniqueChildSlug,
      parentId: parent.id,
      level: 1,
      path: `${parent.slug}/${rawChildSlug}`,
      sortOrder: index,
      isActive: true,
      isFeatured: false,
    },
  });
}

async function main() {
  console.log("Final kategori seed başlıyor...");

  for (let i = 0; i < categoryTree.length; i++) {
    const parentData = categoryTree[i];
    const parent = await upsertParentCategory(parentData, i);

    for (let j = 0; j < parentData.children.length; j++) {
      await upsertChildCategory(parent, parentData.children[j], j);
    }
  }

  const totalCategories = await prisma.category.count();
  console.log(`Seed tamamlandı. Toplam kategori sayısı: ${totalCategories}`);
}

main()
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });